apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name:	wps
build:
  tagPolicy:
    sha256: {}
#    dateTime:
#      format: "2006-01-02_15-04-05.999_MST"
#      timezone: "Local"
  artifacts:
  - image: gcr.io/costin-istio/wps
    #image: costinm/wps
    context: .

#    kaniko:
#      buildContext:
#        gcsBucket: costin-istio

  # 2m for 1-line change
  #googleCloudBuild:
  # projectId: costin-istio

   # Not working
#  cluster:
#     namespace: kaniko

    #sync:	# 	beta local files synced to pods instead of triggering an image build when modified.
    # manual:	# 	manual sync rules indicating the source and destination.
      #- src: "css/**/*.css"	# 	a glob pattern to match local paths against. Directories should be delimited by / on all platforms.
      # dest: "app/"	# 	destination path in the container where the files should be synced to.
      #strip: "css/"	# 	specifies the path prefix to remove from the source path when transplanting the files into the destination folder.
     #infer: []

    custom:
      buildCommand: make docker.push
      dependencies:
        paths:
          - .

#  local:
#      useBuildkit: true

deploy:
    kustomize:
      path: k8s/test


portForward:
  - resourceType: deployment
    namespace: wps
    resourceName: wps
    port: 8080
