apiVersion: v1
kind: ReplicationController
metadata:
  name: dind
  namespace: dind
  labels:
    app: dind
spec:
  replicas: 1
  selector:
    app: dind
  template:
    metadata:
      labels:
        app: dind
        ver: v1
      annotations:
        sidecar.istio.io/interceptionMode: NONE
        sidecar.istio.io/proxyImage: costinm/proxyv2:latest
    spec:
      containers:
        - name: dind
          image: docker:18.05-dind
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375
              name: dind
              protocol: TCP
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker

      volumes:
#        - name: dind-storage
#          emptyDir: {}

        - name: dind-storage
          persistentVolumeClaim:
              claimName: dind
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: dind
spec:
  egress:
    - hosts:
        - "./*"
