apiVersion: skaffold/v1
kind: Config
metadata:
  name:    istio-gw-hostport
deploy:
  kubectl:
    manifests:
      - ns.yaml
      - charts/*.yaml
portForward:
  - resourceType: daemonset
    namespace: istio-gw-hotspot
    resourceName: gate
    port: 15000
    localPort: 12000
