apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-registry

resources:
  - ns.yaml
  - charts/pd.yaml
  - charts/app.yaml
  - charts/service.yaml
  - charts/registry_proxy.yaml
  - charts/istio.yaml
