apiVersion: skaffold/v1
kind: Config
metadata:
  name:    kube-registry
deploy:
  kubectl:
    manifests:
      - ns.yaml
      - charts/*.yaml

#portForward:
#   - resourceType: replicationcontroller
#     namespace: kube-registry
#     resourceName: kube-registry-v0
#     port: 5000
#     localPort: 5000

#  - resourceType: service
#    namespace: kube-registry
#    resourceName: kube-registry
#    port: 5000
#    localPort: 5001

