apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-registry
  labels:
    app: kube-registry
spec:
  selector:
    app: kube-registry
  ports:
    - name: http-registry
      port: 5000
      protocol: TCP
