apiVersion: v1
kind: Service
metadata:
  name: wpslb
  namespace: wps
spec:
  selector:
    app: wps
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: tls-dns
      port: 953
      protocol: TCP
    - name: syncthing
      port: 8384
      protocol: TCP
    - name: ssh
      port: 5222
      protocol: TCP
    - name: h2-dmesh
      port: 5228
      protocol: TCP

---
# https://github.com/kubernetes/kubernetes/issues/23880
# Can't create UDP + TCP LB - workaround is to create 2 services,
# and use the first service IP.
