apiVersion: v1
kind: Service
metadata:
  name: wpslb
  namespace: wps
spec:
  selector:
    app: wps
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: tls-dns
      port: 953
      protocol: TCP
    - name: ssh
      port: 15022
      protocol: TCP
    - name: h2-xds
      port: 15012
      protocol: TCP
