---
apiVersion: v1
kind: Service
metadata:
  name: wps
  namespace: wps
  labels:
    release: wps
spec:
  ports:
    - port: 15022
      name: ssh
  selector:
    app: wps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wps
  namespace: wps
  labels:
    app: wps
    release: wps
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wps
  template:
    metadata:
      labels:
        app: wps
    spec:
      serviceAccountName: default
      containers:
        - name: app
          #image: localhost:5000/wps:2020-05-24
          #image: localhost:5000/wps:2020-05-24
          image: wps:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: noise1
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 30
#            timeoutSeconds: 5
          envFrom:
          - configMapRef:
              name: wps
              optional: true
          env:
            - name: GOTRACEBACK
              value: "all"
          resources:
            requests:
              cpu: 800m
              memory: 2048Mi
          volumeMounts:
            - name: wps
              mountPath: /var/lib/wps
              readOnly: true
      securityContext:
        runAsUser: 0
        runAsGroup: 5228
      volumes:
        - emptyDir:
            medium: Memory
          name: local-certs
        - name: wps
          configMap:
            name: wps
            optional: true
