# Runs a docker-mounted dev image.
# Can build images in the node's docker.
apiVersion: v1
kind: ReplicationController
metadata:
  name: docker
  namespace: dev
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    app: docker
  template:
    metadata:
      labels:
        app: docker
      annotations:
        sidecar.istio.io/proxyImage: costinm/proxyv2:latest
    spec:
      containers:
        - name: ubuntu
          #image: ubuntu
          image: gcr.io/istio-testing/build-tools:master-2020-05-20T22-13-03
          command: [ "sleep" ]
          args: [ "infinity" ]

          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
          - mountPath: /work
            name: src

          securityContext:
            privileged: true
          ports:
            - containerPort: 5000
              name: docker
              protocol: TCP

      volumes:
        - name: docker-socket-volume
          hostPath:
              path: /var/run/docker.sock
              type: File

        - name: src
          persistentVolumeClaim:
              claimName: src

