apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: dev
spec:
  egress:
    - hosts:
        - "./*"

---
apiVersion: v1
kind: Service
metadata:
  name: dev
  namespace: dev
spec:
  selector:
    app: dev
  ports:
    - name: tcp-syncthing
      port: 8384
      protocol: TCP
    - name: tcp-ssh
      port: 5222
      protocol: TCP
    - name: https-wps
      port: 5228
      protocol: TCP
