# Start a remote docker machine for debug/dev

# Forward registry port to 5001
# In-cluster registry runs on localhost:5001

# Also forwards Istio ports for debug

apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name:	dind
deploy:
  kubectl:
    manifests:
      - ns.yaml
      - charts/*.yaml

portForward:
  - resourceType: replicationcontroller
    namespace: dind
    resourceName: dind
    port: 2375
    localPort: 2375

